exports.dateKeywords = ["today","tomorrow","yesterday"];
exports.monthsLong = ['january', 'february', 'march', 'april', 'may', 'june', 'july', 'august', 'september', 'october', 'november', 'december'];
exports.monthsShort = ['jan', 'feb', 'mar', 'apr', 'may', 'june', 'july', 'aug', 'sept', 'oct', 'nov', 'dec'];
exports.creditKeywords = ['owe','borrow','credit','arrear'];
exports.debitKeywords = ['spend','spent','paid','bought'];
exports.users = ['i','all'];
exports.members = [];
exports.emails = [];
exports.count = 5;